name: PR Checks
on:
  pull_request:
    types: ["opened", "edited", "reopened", "synchronize"]
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1
    outputs:
      version_tag: ${{ steps.tag_version.outputs.new_tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Login to Docker hub
        id: login-docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Go Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Dependencies
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          GIT_USER: ${{ secrets.GIT_USER }}
          GIT_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: make ci step=setup

      - name: Lint
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: make ci step=lint

      - name: Build CI runner
        run: make docker-build
